### ISSUE TITLE
Error occuring on login if using kkthnx unitframes

### ISSUE THREAD

**Issue by Jozh89** [Kkthnx-Wow/KkthnxUI_Wrath#1]
Message: ...ddOns\KkthnxUI\Libraries\oUF\elements\classpower.lua:163: attempt to index field '?' (a nil value)
Time: Sat Aug 13 01:06:54 2022
Count: 1
Stack: ...ddOns\KkthnxUI\Libraries\oUF\elements\classpower.lua:163: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\KkthnxUI\Libraries\oUF\elements\classpower.lua"]:163: in function <...ddOns\KkthnxUI\Libraries\oUF\elements\classpower.lua:159>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua"]:212: in function <Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:193>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: self = oUF_Player {
 0 = <userdata>
 Highlight = <unnamed> {
 }
 PARTY_LOOT_METHOD_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\masterlooterindicator.lua:82
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:252
 mystyle = "player"
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:292
 unitEvents = <table> {
 }
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\health.lua:184
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\restingindicator.lua:58
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:252
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:252
 PLAYER_REGEN_DISABLED = <table> {
 }
 style = "Player"
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\raidtargetindicator.lua:62
 UNIT_CONNECTION = <table> {
 }
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:243
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:270
 ThreatIndicator = <table> {
 }
 Overlay = <unnamed> {
 }
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\portrait.lua:87
 HealthPrediction = <table> {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:54
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\resurrectindicator.lua:60
 UNIT_POWER_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Modules\UnitFrames\Plugins\oUF_EnergyManaRegen.lua:76
 UNIT_HEALTH_FREQUENT = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\health.lua:184
 PORTRAITS_UPDATED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\portrait.lua:87
 __elements = <table> {
 }
 PARTY_MEMBER_ENABLE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\health.lua:132
 Power = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:252
 DebuffHighlight = <unnamed> {
 }
 DebuffHighlightFilter = true
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\threatindicator.lua:104
 UNIT_HEALTH = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\health.lua:184
 Health = <unnamed> {
 }
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\leaderindicator.lua:59
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface\AddOns\KkthnxUI\Modules\UnitFrames\Plugins\oUF_EnergyManaRegen.lua:76
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:358
 AssistantIndicator = <unnamed> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:193
 Portrait = KKUI_PlayerPortrait {
 }
 UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\castbar.lua:165
 ReadyCheckIndicator

**Comment by Jozh89** [comment]
![image](https://user-images.githubusercontent.com/56223893/184385644-10e17bfe-5109-4226-86c4-a128d9c43c29.png)

**Comment by Kkthnx** [comment]
Should be fixed.
